# local 개발용 docker-compose
version: '3.8'
services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  redis_data:
