server:
  port: 8081
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/poker?autoReconnect=true
    hikari:
      username: root
      password: local
      pool-name: hikari-cp
      minimum-idle: 10
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  data:
    redis:
      port: 6379
      host: localhost
